# If launch in i3/config the scratchpads are not spawn (race condition?)
urxvtd -o -q -f

# merge .Xressources file
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# set the keyboard lang
setxkbmap -layout fr

exec i3

